// GENERATED by @edgedb/generate v0.5.3

import * as $ from "../reflection";
import * as _ from "../imports";
import _module__ai from "./ext/ai";
import _module__pgvector from "./ext/pgvector";
import _module__pg_trgm from "./ext/pg_trgm";


type __defaultExports = {
  "ai": typeof _module__ai;
  "pgvector": typeof _module__pgvector;
  "pg_trgm": typeof _module__pg_trgm
};
const __defaultExports: __defaultExports = {
  "ai": _module__ai,
  "pgvector": _module__pgvector,
  "pg_trgm": _module__pg_trgm
};
export default __defaultExports;
